### PR TITLE
Add sanity checks to see java and midonet-cluster processes are running

### PR DESCRIPTION
**Pull request by saptaktakalkar**
JIRA: [AN-86](https://midobugs.atlassian.net/browse/AN-86)

### CODE REVIEW

**Comment by abelboldu** [comment]
Those checks don't seem to be idempotent (they will report a `changed` state on the next run)
Can we look for a idempotent approach?

**Comment by saptaktakalkar** [comment]
Does it have to be idempotent? Since, it will be helpful for us to check the state of this task and this sanity check is for testing purpose only.

**Comment by abelboldu** [comment]
Yes, it has to be.

Travis will do idempotency tests on this role too, see openstack ones

**Comment by saptaktakalkar** [comment]
I could only think of `changed_when` to make this idempotent.

**Pull request merged**
